#!/usr/bin/env python3
"""
Model Export Utility

Export fine-tuned models to various formats:
- Ollama (for local inference)
- GGUF (for llama.cpp)
- HuggingFace (for sharing)
"""

import os
import json
import shutil
import argparse
import subprocess
from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.progress import Progress


console = Console()


def export_to_ollama(
    model_path: str,
    model_name: str,
    quantization: str = "q4_k_m",
) -> bool:
    """Export model to Ollama format."""
    
    model_dir = Path(model_path)
    
    if not model_dir.exists():
        console.print(f"[red]Model path not found: {model_path}[/red]")
        return False
    
    console.print(f"\n[bold]Exporting to Ollama: {model_name}[/bold]")
    
    # Check for required files
    required_files = ["config.json", "tokenizer.json"]
    adapter_files = ["adapter_config.json", "adapter_model.safetensors"]
    
    has_adapter = all((model_dir / f).exists() for f in adapter_files)
    
    if has_adapter:
        console.print("  Found LoRA adapter, will merge before export")
    
    # Create Modelfile for Ollama
    modelfile_content = f"""# Modelfile for {model_name}
# Generated by Shrike AI Lab

FROM {model_dir}

PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER stop "<|im_end|>"

TEMPLATE \"\"\"{{{{.System}}}}

{{{{.Prompt}}}}\"\"\"
"""
    
    modelfile_path = model_dir / "Modelfile"
    modelfile_path.write_text(modelfile_content)
    console.print(f"  Created Modelfile")
    
    # If this is a LoRA adapter, we need to merge first
    if has_adapter:
        console.print("  Merging LoRA adapter with base model...")
        
        # Try to merge using transformers
        try:
            merge_lora_adapter(model_dir)
            console.print("  [green]✓ Adapter merged[/green]")
        except Exception as e:
            console.print(f"  [yellow]⚠ Could not merge: {e}[/yellow]")
            console.print("  Continuing with adapter export...")
    
    # Import to Ollama
    console.print(f"  Importing to Ollama as {model_name}...")
    
    result = subprocess.run(
        ["docker", "exec", "shrike-ollama", "ollama", "create", model_name, "-f", str(modelfile_path)],
        capture_output=True,
        text=True,
    )
    
    if result.returncode == 0:
        console.print(f"  [green]✓ Successfully exported to Ollama[/green]")
        console.print(f"\n  Test with: ollama run {model_name}")
        return True
    else:
        console.print(f"  [red]✗ Export failed: {result.stderr}[/red]")
        return False


def merge_lora_adapter(model_dir: Path):
    """Merge LoRA adapter with base model."""
    
    try:
        from peft import PeftModel
        from transformers import AutoModelForCausalLM, AutoTokenizer
    except ImportError:
        raise ImportError("Install peft and transformers to merge adapters")
    
    # Load adapter config to get base model
    adapter_config_path = model_dir / "adapter_config.json"
    with open(adapter_config_path) as f:
        adapter_config = json.load(f)
    
    base_model_name = adapter_config.get("base_model_name_or_path")
    
    if not base_model_name:
        raise ValueError("Could not find base model in adapter config")
    
    console.print(f"  Loading base model: {base_model_name}")
    
    # Load base model
    base_model = AutoModelForCausalLM.from_pretrained(
        base_model_name,
        torch_dtype="auto",
        device_map="auto",
    )
    
    # Load adapter
    model = PeftModel.from_pretrained(base_model, str(model_dir))
    
    # Merge
    merged_model = model.merge_and_unload()
    
    # Save merged model
    merged_dir = model_dir / "merged"
    merged_dir.mkdir(exist_ok=True)
    
    merged_model.save_pretrained(merged_dir)
    
    # Copy tokenizer
    tokenizer = AutoTokenizer.from_pretrained(str(model_dir))
    tokenizer.save_pretrained(merged_dir)
    
    console.print(f"  Saved merged model to {merged_dir}")


def export_to_gguf(
    model_path: str,
    output_path: str,
    quantization: str = "q4_k_m",
) -> bool:
    """Export model to GGUF format for llama.cpp."""
    
    console.print(f"\n[bold]Exporting to GGUF: {output_path}[/bold]")
    console.print(f"  Quantization: {quantization}")
    
    # Check for llama.cpp convert script
    llama_cpp_path = os.getenv("LLAMA_CPP_PATH", "~/llama.cpp")
    convert_script = Path(llama_cpp_path).expanduser() / "convert-hf-to-gguf.py"
    
    if not convert_script.exists():
        console.print(f"[red]llama.cpp not found at {llama_cpp_path}[/red]")
        console.print("Set LLAMA_CPP_PATH environment variable or install llama.cpp")
        return False
    
    # Convert to GGUF
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    result = subprocess.run(
        [
            "python", str(convert_script),
            model_path,
            "--outfile", str(output_file),
            "--outtype", quantization,
        ],
        capture_output=True,
        text=True,
    )
    
    if result.returncode == 0:
        console.print(f"  [green]✓ Exported to {output_file}[/green]")
        
        # Show file size
        size_mb = output_file.stat().st_size / (1024 * 1024)
        console.print(f"  File size: {size_mb:.1f} MB")
        return True
    else:
        console.print(f"  [red]✗ Export failed: {result.stderr}[/red]")
        return False


def export_to_huggingface(
    model_path: str,
    repo_id: str,
    private: bool = True,
) -> bool:
    """Upload model to HuggingFace Hub."""
    
    console.print(f"\n[bold]Uploading to HuggingFace: {repo_id}[/bold]")
    
    try:
        from huggingface_hub import HfApi, create_repo
    except ImportError:
        console.print("[red]Install huggingface_hub: pip install huggingface_hub[/red]")
        return False
    
    # Check for HF token
    hf_token = os.getenv("HF_TOKEN")
    if not hf_token:
        console.print("[red]HF_TOKEN environment variable not set[/red]")
        return False
    
    api = HfApi(token=hf_token)
    
    # Create repo if needed
    try:
        create_repo(repo_id, private=private, token=hf_token, exist_ok=True)
        console.print(f"  Repository: https://huggingface.co/{repo_id}")
    except Exception as e:
        console.print(f"  [yellow]Repo exists or error: {e}[/yellow]")
    
    # Upload
    console.print("  Uploading model files...")
    
    api.upload_folder(
        folder_path=model_path,
        repo_id=repo_id,
        token=hf_token,
    )
    
    console.print(f"  [green]✓ Uploaded to https://huggingface.co/{repo_id}[/green]")
    return True


def list_local_models():
    """List locally trained models."""
    
    models_dir = Path("models")
    
    if not models_dir.exists():
        console.print("[yellow]No models directory found[/yellow]")
        return
    
    console.print("\n[bold]Local Models[/bold]\n")
    
    for model_dir in sorted(models_dir.iterdir()):
        if not model_dir.is_dir():
            continue
        
        # Check for training metadata
        metadata_file = model_dir / "training_metadata.json"
        
        if metadata_file.exists():
            with open(metadata_file) as f:
                metadata = json.load(f)
            
            console.print(f"[cyan]{model_dir.name}[/cyan]")
            console.print(f"  Project: {metadata.get('project', 'unknown')}")
            console.print(f"  Task: {metadata.get('task', 'unknown')}")
            console.print(f"  Trained: {metadata.get('trained_at', 'unknown')[:10]}")
            console.print(f"  Examples: {metadata.get('training_examples', 'unknown')}")
        else:
            console.print(f"[cyan]{model_dir.name}[/cyan] (no metadata)")
        
        console.print()


def main():
    parser = argparse.ArgumentParser(description="Export fine-tuned models")
    subparsers = parser.add_subparsers(dest="command", help="Export target")
    
    # List command
    list_parser = subparsers.add_parser("list", help="List local models")
    
    # Ollama export
    ollama_parser = subparsers.add_parser("ollama", help="Export to Ollama")
    ollama_parser.add_argument("--model", "-m", required=True, help="Model path")
    ollama_parser.add_argument("--name", "-n", required=True, help="Ollama model name")
    ollama_parser.add_argument("--quantization", "-q", default="q4_k_m", help="Quantization type")
    
    # GGUF export
    gguf_parser = subparsers.add_parser("gguf", help="Export to GGUF")
    gguf_parser.add_argument("--model", "-m", required=True, help="Model path")
    gguf_parser.add_argument("--output", "-o", required=True, help="Output GGUF file")
    gguf_parser.add_argument("--quantization", "-q", default="q4_k_m", help="Quantization type")
    
    # HuggingFace export
    hf_parser = subparsers.add_parser("huggingface", help="Upload to HuggingFace")
    hf_parser.add_argument("--model", "-m", required=True, help="Model path")
    hf_parser.add_argument("--repo", "-r", required=True, help="HuggingFace repo ID")
    hf_parser.add_argument("--public", action="store_true", help="Make repo public")
    
    args = parser.parse_args()
    
    if args.command == "list":
        list_local_models()
    elif args.command == "ollama":
        export_to_ollama(args.model, args.name, args.quantization)
    elif args.command == "gguf":
        export_to_gguf(args.model, args.output, args.quantization)
    elif args.command == "huggingface":
        export_to_huggingface(args.model, args.repo, not args.public)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
