#!/usr/bin/env python3
"""qa/contract_fuzz.py + qa/contract_fuzz_cron.sh (QA-N2: hermetic Schemathesis contract fuzz, shadow only).

Part 1 (stdlib only, runs anywhere): report parser on committed fixtures, signature/baseline/fingerprint logic, redactor, config table, the
cron wrapper (kill switch / PAUSED / load / lock), and the "not a gate_*.py, qa_run_shadow.sh untouched" invariants.
Part 2 (needs schemathesis + a python with fastapi/uvicorn, i.e. the box): the real CLI against a tiny stub FastAPI app committed into a temp git
repo (variants are real commits, so "the 500 removed" is a real code change at a different SHA). The stub app runs under a python that has
fastapi+uvicorn (OVN_FUZZ_TEST_APP_PYTHON, the running python, ~/qa-venv, or the iptv_apps repo venv); schemathesis comes from ~/qa-venv
(OVN_FUZZ_SCHEMATHESIS). Without them Part 2 prints 'SKIP: <module> missing' and exits 0 - unless OVN_REQUIRE_QA_VENV is set, then it FAILS.
Mutation checks (M1..M16) copy the module with ONE line broken and prove the corresponding assertion would have failed.
No network: the stub's outbound probes use RFC 5737 / .invalid addresses and are blocked by the guard under test."""
import atexit
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
QA = os.path.join(ROOT, "qa")
SCRIPT = os.path.join(QA, "contract_fuzz.py")
CRON = os.path.join(QA, "contract_fuzz_cron.sh")
FIX = os.path.join(HERE, "fixtures", "contract_fuzz")
sys.path.insert(0, QA)
import contract_fuzz as cf  # noqa: E402

P = F = 0


def ok(name, cond, extra=""):
    global P, F
    if cond:
        P += 1
        print("  ok   " + name)
    else:
        F += 1
        print("  FAIL " + name + ((" :: " + str(extra)[:400]) if extra else ""))


WORK = tempfile.mkdtemp(prefix="cftest-")
atexit.register(shutil.rmtree, WORK, True)      # also on a crash
TMPD = os.path.join(WORK, "tmp")          # TMPDIR of every fuzz run: lets us prove nothing is left behind
os.makedirs(TMPD)
_n = [0]


def alive(pid):
    """ps-stat based liveness (never kill -0 on a reaped/killed child): a zombie or a missing pid is not alive."""
    r = subprocess.run(["ps", "-o", "stat=", "-p", str(pid)], capture_output=True, text=True)
    st = r.stdout.strip()
    return bool(st) and not st.startswith("Z")


def fresh(label):
    _n[0] += 1
    d = os.path.join(WORK, "%s-%d" % (label, _n[0]))
    os.makedirs(d)
    return d


# =============================================================================================== PART 1: stdlib-only unit tests
print("== parser (committed fixtures generated by running schemathesis 4.28.0 on the box against the stub)")


def fx(name):
    return os.path.join(FIX, name)


def pf(name):
    try:
        return cf.parse_ndjson(fx(name))
    except OSError:
        ok("fixture %s exists" % name, False)
        return {"complete": False, "signatures": [], "version": None, "seed": None, "operations_total": None, "operations_selected": None}


p = pf("clean.ndjson")
ok("fixture clean: complete run, zero signatures", p["complete"] and p["signatures"] == [], p)
ok("fixture clean: schemathesis version + seed captured", p["version"] == "4.28.0" and p["seed"] == 42, p)
ok("fixture clean: operation counts captured", p["operations_total"] and p["operations_selected"] and p["operations_total"] >= p["operations_selected"], p)
p = pf("boom_bad.ndjson")
ok("fixture boom_bad: the 500 becomes 'GET /boom [not_a_server_error] 500'", "GET /boom [not_a_server_error] 500" in p["signatures"], p["signatures"])
ok("fixture boom_bad: the schema violation becomes 'GET /badschema [response_schema_conformance] JsonSchemaError@200'",
   "GET /badschema [response_schema_conformance] JsonSchemaError@200" in p["signatures"], p["signatures"])
ok("fixture boom_bad: exactly those two (no noise from the healthy routes)", len(p["signatures"]) == 2, p["signatures"])
ok("fixture boom_bad: signatures sorted and unique", p["signatures"] == sorted(set(p["signatures"])))
p = pf("timeout.ndjson")
ok("fixture timeout: a ReadTimeout is 'GET /slow [network_error] ReadTimeout'", "GET /slow [network_error] ReadTimeout" in p["signatures"], p["signatures"])


def ev(kind, **body):
    return json.dumps({kind: body})


def write_lines(lines):
    path = os.path.join(fresh("ndjson"), "r.ndjson")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def scenario(label, checks, status_code):
    return ev("ScenarioFinished", status="failure", recorder={"label": label, "checks": {"c1": checks},
                                                                "interactions": {"c1": {"response": {"status_code": status_code}}}})


fin = ev("EngineFinished", stop_reason="completed", payload={})
p = cf.parse_ndjson(write_lines([
    "not json at all", "", "[1,2]", json.dumps({"a": 1, "b": 2}),
    ev("Initialize", schemathesis_version="9.9.9", seed=7),
    scenario("POST /x/{id}", [{"name": "not_a_server_error", "status": "failure"}, {"name": "response_schema_conformance", "status": "success"}], 503),
    scenario("POST /x/{id}", [{"name": "not_a_server_error", "status": "failure"}], 503),          # duplicate -> one signature
    scenario("GET /y", [{"name": "response_schema_conformance", "status": "failure", "failure_info": {"failure": {"type": "JsonSchemaError"}}}], 201),
    scenario("GET /ok", [{"name": "not_a_server_error", "status": "success"}], 200),
    ev("NonFatalError", value={"type": "ReadTimeout", "message": "secret-looking text tok=abc"}, label="GET /z"),
    ev("NonFatalError", value={"type": "InvalidHeader", "message": "x"}, label="GET /w"),
    fin]))
ok("synthetic: junk lines tolerated, version/seed read", p["version"] == "9.9.9" and p["seed"] == 7, p)
ok("synthetic: 503 + schema failure + timeout are signatures, duplicates collapse, passing checks are not",
   p["signatures"] == ["GET /y [response_schema_conformance] JsonSchemaError@201", "GET /z [network_error] ReadTimeout", "POST /x/{id} [not_a_server_error] 503"],
   p["signatures"])
ok("synthetic: client-side InvalidHeader is counted, not a signature", p["client_errors"] == 1 and not any("InvalidHeader" in s for s in p["signatures"]), p)
ok("synthetic: exception messages never reach a signature", not any("tok=abc" in s or "secret" in s for s in p["signatures"]), p["signatures"])
p = cf.parse_ndjson(write_lines([ev("Initialize", schemathesis_version="1", seed=1), scenario("GET /y", [{"name": "not_a_server_error", "status": "failure"}], 500)]))
ok("NEGATIVE: a truncated report (no EngineFinished) is not complete", p["complete"] is False, p)
p = cf.parse_ndjson(write_lines([fin.replace("completed", "interrupted")]))
ok("NEGATIVE: stop_reason != completed is not complete", p["complete"] is False and p["stop_reason"] == "interrupted", p)

print("== redactor")
SECRET = "s3cr3t-SEEDED-value-9f2c41"
TOKEN = "stub-bearer-token-7f3a91c2d4e8"
r = cf.redact("boot failure: %s and raw token %s tail" % (SECRET, TOKEN), {SECRET, TOKEN})
ok("literal secrets are replaced", SECRET not in r and TOKEN not in r and "***" in r, r)
r = cf.redact("Authorization: Bearer abcdefghij1234 and eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.sig_abc-123 and password=hunter22 and https://user:pw@host/x")
ok("credential-shaped text is scrubbed without being told", all(x not in r for x in ("abcdefghij1234", "eyJhbGciOiJIUzI1NiJ9", "hunter22", "user:pw")), r)
sig = "GET /api/items/{id} [not_a_server_error] 500"
ok("NEGATIVE: an ordinary signature is left intact", cf.redact(sig) == sig, cf.redact(sig))
ok("redactor keeps only a bounded tail", len(cf.redact("x" * 5000, limit=300)) == 300)
ok("secrets_from picks secret-looking env values only", cf.secrets_from({"JWT_SECRET_KEY": "abcd1234", "RATE_LIMIT_ENABLED": "false", "EMPTY_TOKEN": ""}) == {"abcd1234"})

print("== baseline + fingerprint")
os.environ["QA_STATE_DIR"] = fresh("state")
ok("no baseline file => None", cf.load_baseline("r1") is None)
cf.write_baseline("r1", "origin/develop", "abc", "fp1", ["b sig", "a sig"])
b = cf.load_baseline("r1")
ok("write/load round trip (sorted, atomic file in qa_shadow)", b and b["signatures"] == ["a sig", "b sig"] and b["fingerprint"] == "fp1"
   and cf.baseline_path("r1").endswith(os.path.join("qa_shadow", "contract_fuzz_baseline_r1.json")), b)
ok("no temp files left next to the baseline", [x for x in os.listdir(os.path.dirname(cf.baseline_path("r1"))) if x.startswith(".cf_baseline.")] == [])
with open(cf.baseline_path("r2"), "w") as f:
    f.write("{corrupt")
ok("NEGATIVE: a corrupt baseline reads as missing (never raises)", cf.load_baseline("r2") is None)
base_params = {"seed": 42, "max_examples": 25, "checks": cf.CHECKS, "phases": cf.PHASES, "mode": "all", "schemathesis": "4.28.0"}
fp0 = cf.fingerprint(base_params, ["a", "b"])
ok("fingerprint is stable and order-insensitive for excludes", fp0 == cf.fingerprint(dict(base_params), ["b", "a"]))
ok("fingerprint changes with seed, max_examples, excludes and schemathesis version",
   len({fp0, cf.fingerprint(dict(base_params, seed=7), ["a", "b"]), cf.fingerprint(dict(base_params, max_examples=5), ["a", "b"]),
        cf.fingerprint(base_params, ["a"]), cf.fingerprint(dict(base_params, schemathesis="4.29.0"), ["a", "b"])}) == 5)
del os.environ["QA_STATE_DIR"]

print("== command line, credentials, kill_group (stdlib-only)")
_args = cf.fuzz_args(42, 25, "all", 15, ["^/a$", "^/b$"])


def adj(lst, *seq):
    return any(lst[i:i + len(seq)] == list(seq) for i in range(len(lst) - len(seq) + 1))


ok("fuzz_args: single worker, restricted phases, 5xx+schema checks only, fixed seed, request timeout",
   adj(_args, "-w", "1") and adj(_args, "--phases", "examples,fuzzing") and adj(_args, "--checks", cf.CHECKS) and adj(_args, "--seed", "42")
   and adj(_args, "--request-timeout", "15") and adj(_args, "-n", "25") and "--no-shrink" in _args and "--generation-deterministic" in _args, _args)
ok("fuzz_args: the exclude regex is passed", adj(_args, "--exclude-path-regex", "(?:^/a$)|(?:^/b$)"), _args)
_cmd = cf.build_cmd("/x/schemathesis", "/t/o.json", "http://127.0.0.1:1", "/t/rep", _args, "/t/st.toml")
_pre = cf.qc.cpu_prefix()
ok("build_cmd: starts with the nice (+ionice/cpuset) prefix, then the schemathesis binary", _cmd[:len(_pre)] == _pre and _cmd[len(_pre)] == "/x/schemathesis" and "nice" in _pre, _cmd[:8])
ok("build_cmd: carries every fuzz arg, the report dir and the config file", all(a in _cmd for a in _args) and adj(_cmd, "--report-dir", "/t/rep") and adj(_cmd, "--config-file", "/t/st.toml"), _cmd)
ok("build_cmd: no credential flag on argv (token travels via config file + env var)", "-H" not in _cmd and "--header" not in _cmd and "-a" not in _cmd
   and "FUZZ_TOKEN" in cf.TOKEN_CONFIG and "Bearer" in cf.TOKEN_CONFIG and "stub-bearer" not in " ".join(_cmd))
fp_a = cf.fingerprint(dict(base_params, argv=cf.fuzz_args(42, 25, "all", 15, [])), [])
ok("fingerprint covers the REAL argv: a different request timeout / worker count / phases is a different fingerprint",
   len({fp_a, cf.fingerprint(dict(base_params, argv=cf.fuzz_args(42, 25, "all", 30, [])), []),
        cf.fingerprint(dict(base_params, argv=cf.fuzz_args(42, 25, "all", 15, []) + ["-w", "4"]), [])}) == 3)
_flt = cf.retry_filter(["GET /a/{id} [network_error] ReadTimeout", "POST /b [not_a_server_error] 500", "GET /c [network_error] ConnectionError"])
ok("retry_filter matches exactly the timed-out operations (templates escaped), nothing else",
   re.search(_flt, "GET /a/{id}") and re.search(_flt, "GET /c") and not re.search(_flt, "POST /b") and not re.search(_flt, "GET /a/{idx}")
   and not re.search(_flt, "GET /c/x"), _flt)
ok("retry_filter is None when nothing is transient (a 500 or a schema error is never re-checked away)",
   cf.retry_filter(["GET /x [not_a_server_error] 500", "GET /y [response_schema_conformance] JsonSchemaError@200", "GET /z [network_error] SomethingElse"]) is None)


class _Gone(object):
    """A leader that was already reaped (poll() != None) whose pid now belongs to somebody else."""
    def __init__(self, pid):
        self.pid = pid

    def poll(self):
        return 0

    def wait(self, timeout=None):
        return 0


victim = subprocess.Popen(["sleep", "60"], start_new_session=True)       # an UNRELATED process that leads its own group
time.sleep(0.2)
cf.kill_group(_Gone(victim.pid))
ok("kill_group never signals a pid whose leader is already reaped (recycled-pid safety)", alive(victim.pid))
cf.sweep_group(_Gone(victim.pid))
time.sleep(0.3)
ok("control: sweep_group (the right-after-exit straggler sweep) does signal that group", not alive(victim.pid))
victim.wait()
lead = subprocess.Popen(["sh", "-c", "sleep 60 & echo $!"], start_new_session=True, stdout=subprocess.PIPE, text=True)
straggler = int(lead.stdout.readline().strip())
lead.wait()
ok("straggler control: the leader is gone, its same-group child is still alive", alive(straggler))
cf.sweep_group(lead)
time.sleep(0.3)
ok("sweep_group kills a straggler right after the leader's exit was observed", not alive(straggler))
live = subprocess.Popen(["sh", "-c", "sleep 60 & echo $!; wait"], start_new_session=True, stdout=subprocess.PIPE, text=True)
kid = int(live.stdout.readline().strip())
cf.kill_group(live, grace=2)
time.sleep(0.3)
ok("kill_group on a live leader kills the leader and its group child", live.poll() is not None and not alive(kid) and not alive(live.pid))

print("== configuration table")
c = cf.config("iptv_apps")
ok("iptv_apps is configured with an exclude list and an auth bootstrap", c and len(c["exclude_paths"]) >= 10 and c["auth"] and c["app"] == "app.main:app")
ok("every exclude pattern compiles", all(re.compile(rx) for rx, _ in c["exclude_paths"]))
ex = [rx for rx, _ in c["exclude_paths"]]
for pth in ("/api/streams/import", "/api/streams/import/m3u", "/api/streams/relay", "/api/streams/{stream_id}/proxy", "/api/streams/{stream_id}/check",
            "/api/streams/sources/{source_id}/refresh", "/api/epg/sources/{source_id}/auto-map", "/api/discover/channels", "/api/subscription/apple/verify",
            "/api/auth/password/forgot", "/api/account/me"):
    ok("iptv exclusion policy covers %s" % pth, any(re.search(rx, pth) for rx in ex))
for pth in ("/api/streams", "/api/favorites/{stream_id}", "/api/settings", "/api/epg/sources", "/health", "/api/subscription/revenuecat/webhook"):
    ok("NEGATIVE: %s is still fuzzed" % pth, not any(re.search(rx, pth) for rx in ex))
ok("unknown repo => None", cf.config("no-such-repo") is None)
ok("every other repo is 'not configured' for now", all(cf.config(r) is None for r in ("billwatch", "gitlark", "xlite", "test-automation-agent")))
override = os.path.join(fresh("cfg"), "c.json")
with open(override, "w") as f:
    json.dump({"zzz": {"clone": "zzz", "app_dir": "a", "venv_python": ["/x"], "app": "m:app", "exclude_paths": ["^/a", ["^/b", "why"]]}}, f)
os.environ["OVN_FUZZ_CONFIG_JSON"] = override
z = cf.config("zzz")
ok("OVN_FUZZ_CONFIG_JSON adds a repo; plain and pair excludes both accepted", z and z["exclude_paths"] == [("^/a", ""), ("^/b", "why")] and cf.config("iptv_apps"), z)
del os.environ["OVN_FUZZ_CONFIG_JSON"]

print("== invariants: not a gate_*.py, qa_run_shadow.sh untouched")
ok("module is not named gate_*.py", not os.path.basename(SCRIPT).startswith("gate_"))
ok("qa_run_shadow.sh's gate_*.py glob cannot pick it up", "contract_fuzz.py" not in [os.path.basename(x) for x in __import__("glob").glob(os.path.join(QA, "gate_*.py"))])
ok("qa_run_shadow.sh does not mention it", "contract_fuzz" not in open(os.path.join(QA, "qa_run_shadow.sh")).read())
ok("no enforce path: the module never emits FAIL", '"FAIL"' not in open(SCRIPT).read().replace("verdicts:", ""))


# =============================================================================================== cron wrapper
print("== contract_fuzz_cron.sh")


def cron(ovn, extra_env=None, script=CRON, cwd=None, rel=None):
    env = {"PATH": "/usr/bin:/bin", "HOME": ovn, "OVN_DIR": ovn, "NTFY_SERVER": "http://127.0.0.1:9", "OVN_FUZZ_REPOS": "no-such-repo",
           "OVN_FUZZ_LOAD_MAX": "100000"}      # the suite must not depend on the host load: only the load cases lower the limit
    env.update(extra_env or {})
    cmd = ["bash", rel or script]
    p = subprocess.run(cmd, env=env, cwd=cwd, capture_output=True, text=True, timeout=120)
    log = os.path.join(ovn, "logs", "contract_fuzz.log")
    return p.returncode, (open(log).read() if os.path.exists(log) else "")


def fresh_ovn():
    d = fresh("ovn")
    os.makedirs(os.path.join(d, "state"))
    return d


o = fresh_ovn()
rc, log = cron(o)
ok("normal run (env -i style, absolute path): exits 0, one summary line with verdict + reason", rc == 0 and log.count("\n") == 1 and "no-such-repo" in log and "NA | repo not configured" in log, log)
o = fresh_ovn()
rc, log = cron(o, cwd=os.path.dirname(ROOT + "/x"), rel=os.path.join("qa", "contract_fuzz_cron.sh"))
ok("normal run via a RELATIVE path from the overnight-queue dir", rc == 0 and "NA | repo not configured" in log, log)
o = fresh_ovn()
rc, log = cron(o, {"OVN_CONTRACT_FUZZ": "off"})
ok("kill switch OVN_CONTRACT_FUZZ=off => logged, nothing ran", rc == 0 and "disabled" in log and "repo not configured" not in log, log)
o = fresh_ovn()
open(os.path.join(o, "state", "PAUSED"), "w").close()
rc, log = cron(o)
ok("state/PAUSED => skipped", rc == 0 and "state/PAUSED" in log and "repo not configured" not in log, log)
o = fresh_ovn()
rc, log = cron(o, {"OVN_FUZZ_LOAD_MAX": "-1"})
ok("load average above the limit => skipped", rc == 0 and "load average" in log and "repo not configured" not in log, log)
o = fresh_ovn()
rc, log = cron(o, {"OVN_FUZZ_LOAD_MAX": "100000"})
ok("NEGATIVE control: a high limit lets the run proceed", rc == 0 and "repo not configured" in log, log)
o = fresh_ovn()
lockfile = os.path.join(o, "state", "contract_fuzz.lock")
if shutil.which("flock"):
    import fcntl
    fh = open(lockfile, "w")
    fcntl.flock(fh, fcntl.LOCK_EX | fcntl.LOCK_NB)
    rc, log = cron(o)
    fcntl.flock(fh, fcntl.LOCK_UN)
    fh.close()
else:
    os.makedirs(lockfile + ".d")
    rc, log = cron(o)
ok("a held lock => skipped, exit 0", rc == 0 and "previous run" in log and "repo not configured" not in log, log)
o = fresh_ovn()
rc, log = cron(o, {"OVN_FUZZ_REPOS": "bad/name;x"})
ok("NEGATIVE: a malformed repo name is refused, never executed", rc == 0 and "bad repo name" in log, log)


def mutant_dir(label):
    d = os.path.join(fresh(label), "qa")
    os.makedirs(d)
    for fn in ("contract_fuzz.py", "qa_common.py", "contract_fuzz_cron.sh"):
        shutil.copy(os.path.join(QA, fn), os.path.join(d, fn))
    return d


def mutate(d, fn, old, new):
    path = os.path.join(d, fn)
    s = open(path).read()
    assert s.count(old) == 1, "mutation anchor not unique/present in %s: %r (%d)" % (fn, old, s.count(old))
    open(path, "w").write(s.replace(old, new))
    return path


md = mutant_dir("m-cron-paused")
mutate(md, "contract_fuzz_cron.sh", '[ -e "$STATE/PAUSED" ] &&', '[ -e "$STATE/PAUSED.mutant" ] &&')
o = fresh_ovn()
open(os.path.join(o, "state", "PAUSED"), "w").close()
rc, log = cron(o, script=os.path.join(md, "contract_fuzz_cron.sh"))
ok("MUTATION M9 (PAUSED check broken): the PAUSED assertion above would FAIL", "state/PAUSED" not in log and "repo not configured" in log, log)
md = mutant_dir("m-cron-load")
mutate(md, "contract_fuzz_cron.sh", "l+0 > m+0", "l+0 > m+0+1000000")
o = fresh_ovn()
rc, log = cron(o, {"OVN_FUZZ_LOAD_MAX": "-1"}, script=os.path.join(md, "contract_fuzz_cron.sh"))
ok("MUTATION M10 (load check broken): the load assertion above would FAIL", "load average" not in log and "repo not configured" in log, log)

md = mutant_dir("m-kill-reaped")
mutate(md, "contract_fuzz.py", "if proc is None or proc.poll() is not None:\n        return\n    pgid = proc.pid", "if proc is None:\n        return\n    pgid = proc.pid")
victim = subprocess.Popen(["sleep", "60"], start_new_session=True)
time.sleep(0.2)
subprocess.run([sys.executable, "-c", "import sys; sys.path.insert(0, %r); import contract_fuzz as c\n"
                "class G:\n    pid = %d\n    def poll(self): return 0\n    def wait(self, timeout=None): return 0\nc.kill_group(G())" % (md, victim.pid)],
               capture_output=True, text=True, timeout=60)
time.sleep(0.3)
ok("MUTATION M12 (reaped-leader guard removed): the recycled-pid assertion above would FAIL - the unrelated group is killed", not alive(victim.pid))
victim.kill()
victim.wait()

# =============================================================================================== PART 2: stub app, real CLI
print("== stub app + real schemathesis")
ST_BIN = None
for cand in (os.environ.get("OVN_FUZZ_SCHEMATHESIS"), os.path.expanduser("~/qa-venv/bin/schemathesis"), shutil.which("schemathesis")):
    if cand and os.path.isfile(cand) and os.access(cand, os.X_OK):
        ST_BIN = cand
        break
APP_PY, missing = None, None
for cand in (os.environ.get("OVN_FUZZ_TEST_APP_PYTHON"), sys.executable, os.path.expanduser("~/qa-venv/bin/python"),
             os.path.expanduser("~/overnight-queue/repos/iptv_apps/iptv-backend/.venv/bin/python")):
    if not cand or not os.path.isfile(cand):
        continue
    r = subprocess.run([cand, "-c", "import fastapi, uvicorn"], capture_output=True, text=True)
    if r.returncode == 0:
        APP_PY = cand
        break
    m = re.search(r"No module named '([\w.]+)'", r.stderr)
    missing = missing or (m.group(1) if m else "fastapi")


def finish():
    shutil.rmtree(WORK, ignore_errors=True)
    print("\ncontract_fuzz: %d passed, %d failed" % (P, F))
    sys.exit(1 if F else 0)


if ST_BIN is None or APP_PY is None:
    what = "schemathesis" if ST_BIN is None else (missing or "fastapi")
    if os.environ.get("OVN_REQUIRE_QA_VENV"):
        ok("OVN_REQUIRE_QA_VENV is set but %s is missing: Part 2 cannot be skipped" % what, False)
    else:
        print("SKIP: %s missing (stub-app cases not run; set OVN_REQUIRE_QA_VENV=1 to make this a failure)" % what)
    finish()

SIG_BOOM = "GET /boom [not_a_server_error] 500"
SIG_BOOM2 = "GET /boom2 [not_a_server_error] 500"
SIG_BAD = "GET /badschema [response_schema_conformance] JsonSchemaError@200"
SIG_PRIV = "GET /private [not_a_server_error] 500"
SIG_SLOW = "GET /slow [network_error] ReadTimeout"
SIG_FLAKY = "GET /flaky/{n} [network_error] ReadTimeout"

STUB_HEAD = r'''
import os, subprocess, sys, time
from fastapi import FastAPI, Header
from fastapi.responses import JSONResponse
from pydantic import BaseModel

HITS = os.environ.get("STUB_HITS", "")
SECRET = os.environ.get("STUB_SECRET", "")
TOKEN = "stub-bearer-token-7f3a91c2d4e8"


def hit(msg):
    if HITS:
        with open(HITS, "a") as f:
            f.write(msg + "\n")


PIDS = os.environ.get("STUB_PIDS", "")
if PIDS:
    _child = subprocess.Popen(["sleep", "300"])
    with open(PIDS, "w") as f:
        f.write("%d %d\n" % (os.getpid(), _child.pid))
'''
STUB_BASE = r'''
app = FastAPI()


class Item(BaseModel):
    id: int
    name: str


class Msg(BaseModel):
    text: str


@app.get("/ok")
def ok():
    return {"ok": True}


@app.get("/items/{item_id}")
def item(item_id: int):
    return {"id": item_id, "name": "n"}


@app.post("/echo")
def echo(msg: Msg):
    return {"text": msg.text}


@app.get("/fetch")
def fetch(url: str):
    hit("fetch:" + url[:20])
    return {"fetched": False}


@app.post("/login")
def login():
    return {"access_token": TOKEN}


@app.get("/private")
def private(authorization: str = Header(None)):
    if authorization == "Bearer " + TOKEN:
        raise RuntimeError("private boom")
    return JSONResponse({"detail": "unauthorized"}, status_code=401)
'''
SNIPPETS = {
    "boom": '@app.get("/boom")\ndef boom():\n    raise RuntimeError("kaboom")\n',
    "boom2": '@app.get("/boom2")\ndef boom2():\n    raise RuntimeError("kaboom two")\n',
    "bad": '@app.get("/badschema", response_model=None, responses={200: {"model": Item}})\ndef badschema():\n'
           '    return JSONResponse({"id": "not-an-int", "name": 5})\n',
    "slow": '@app.get("/slow")\ndef slow():\n    time.sleep(60)\n    return {"ok": True}\n',
    "die": '@app.get("/die")\ndef die(authorization: str = Header(None)):\n'
           '    sys.stderr.write("dying: tok:%s boot:%s\\n" % ((authorization or "").replace("Bearer ", ""), SECRET))\n    sys.stderr.flush()\n    os._exit(1)\n',
    "callout": '@app.get("/call-out")\ndef call_out():\n    import socket\n    for tgt in (("stub-host.invalid", 80), ("192.0.2.1", 80)):\n        try:\n'
               '            socket.create_connection(tgt, timeout=1).close()\n            hit("callout:CONNECTED:" + tgt[0])\n        except Exception as e:\n'
               '            hit("callout:%s:%s" % (tgt[0], str(e)[:80]))\n    return {"done": True}\n',
    "acallout": '@app.get("/acall-out")\nasync def acall_out():\n    import asyncio\n    for tgt in (("stub-host.invalid", 80), ("192.0.2.1", 80)):\n        try:\n'
                '            _r, w = await asyncio.wait_for(asyncio.open_connection(tgt[0], tgt[1]), timeout=2)\n            w.close()\n            hit("acallout:CONNECTED:" + tgt[0])\n'
                '        except BaseException as e:\n            hit("acallout:%s:%s:%s" % (tgt[0], type(e).__name__, str(e)[:80]))\n    return {"done": True}\n',
    "flaky": '@app.get("/flaky/{n}")\ndef flaky(n: int):\n    m = os.environ.get("STUB_FLAKY", "")\n    if m and not os.path.exists(m):\n'
             '        open(m, "w").close()\n        time.sleep(4)\n    return {"ok": True}\n',
}
BOOT_FAIL = 'raise RuntimeError("stub boot failure: %s" % SECRET)\n'


def stub_source(*names, boot_fail=False):
    out = STUB_HEAD
    if boot_fail:
        out += BOOT_FAIL
    out += STUB_BASE
    for n in names:
        out += "\n\n" + SNIPPETS[n]
    return out


GIT = ["git", "-c", "user.name=t", "-c", "user.email=t@t", "-c", "commit.gpgsign=false"]
REPOS_DIR = os.path.join(WORK, "repos")
STUB_REPO = os.path.join(REPOS_DIR, "stubrepo")
os.makedirs(os.path.join(STUB_REPO, "svc"))
subprocess.run(["git", "init", "-q", STUB_REPO], check=True)
REFS = {}


def commit_variant(name, *snips, **kw):
    with open(os.path.join(STUB_REPO, "svc", "stub_app.py"), "w") as f:
        f.write(stub_source(*snips, **kw))
    subprocess.run(GIT + ["-C", STUB_REPO, "add", "svc/stub_app.py"], check=True, capture_output=True)
    subprocess.run(GIT + ["-C", STUB_REPO, "commit", "-q", "-m", name], check=True, capture_output=True)
    REFS[name] = subprocess.run(["git", "-C", STUB_REPO, "rev-parse", "HEAD"], check=True, capture_output=True, text=True).stdout.strip()


commit_variant("base")
commit_variant("boom", "boom")
commit_variant("bad", "bad")
commit_variant("boom2", "boom", "boom2")
commit_variant("mixed", "boom", "boom2", "bad")
commit_variant("boombad", "boom", "bad")
commit_variant("slow", "slow")
commit_variant("die", "die")
commit_variant("callout", "callout")
commit_variant("acallout", "acallout")
commit_variant("flaky", "flaky")
commit_variant("failstart", boot_fail=True)
HITS = os.path.join(WORK, "hits.txt")
PIDF = os.path.join(WORK, "pids.txt")


def stub_cfg(path=None, exclude=("^/fetch$",), auth=False, venv=None, pidfile=False, env=None):
    c = {"clone": "stubrepo", "app_dir": "svc", "venv_python": [venv or APP_PY], "app": "stub_app:app", "openapi_path": "/openapi.json",
         "env": {"STUB_HITS": HITS, "STUB_SECRET": SECRET}, "exclude_paths": list(exclude)}
    c["env"].update(env or {})
    if pidfile:
        c["env"]["STUB_PIDS"] = PIDF
    if auth:
        c["auth"] = {"login": {"path": "/login", "json": {}, "token_field": "access_token"}}
    path = path or os.path.join(fresh("cfg"), "cfg.json")
    with open(path, "w") as f:
        json.dump({"stubrepo": c}, f)
    return path


def last_json(out):
    for line in reversed((out or "").strip().splitlines()):
        if line.startswith("{"):
            return json.loads(line)
    return None


def run_fuzz(ref, state, cfgpath=None, args=(), env=None, script=SCRIPT, repo="stubrepo", timeout=420):
    e = {"PATH": "/usr/bin:/bin:/usr/local/bin", "HOME": WORK, "OVN_DIR": WORK, "OVN_REPOS_DIR": REPOS_DIR, "QA_STATE_DIR": state, "TMPDIR": TMPD,
         "OVN_FUZZ_CONFIG_JSON": cfgpath or stub_cfg(), "OVN_FUZZ_SCHEMATHESIS": ST_BIN, "OVN_FUZZ_MAX_EXAMPLES": "8", "NTFY_SERVER": "http://127.0.0.1:9"}
    e.update(env or {})
    t0 = time.time()
    p = subprocess.run([sys.executable, script, "check", "--repo", repo, "--ref", REFS.get(ref, ref)] + list(args), env=e, capture_output=True, text=True,
                       timeout=timeout)
    res = last_json(p.stdout)
    return {"rc": p.returncode, "res": res, "elapsed": time.time() - t0, "out": p.stdout, "err": p.stderr}


def sigs(r):
    return (r["res"] or {}).get("details", {}).get("signatures")


def hits():
    try:
        return open(HITS).read()
    except OSError:
        return ""


def reset_hits():
    try:
        os.unlink(HITS)
    except OSError:
        pass


def leftovers():
    """Temp dirs / worktrees a run left behind (TMPDIR is private to the suite, so any entry is ours)."""
    left = [x for x in os.listdir(TMPD) if x.startswith(("cfuzz-", "qa-wt-"))]
    wl = subprocess.run(["git", "-C", STUB_REPO, "worktree", "list", "--porcelain"], capture_output=True, text=True).stdout
    n_wt = len([ln for ln in wl.splitlines() if ln.startswith("worktree ")])
    return left, n_wt


def shadow_rows(state):
    path = os.path.join(state, "qa_shadow", "contract_fuzz.jsonl")
    return [json.loads(ln) for ln in open(path).read().splitlines() if ln.strip()] if os.path.exists(path) else []


if os.environ.get("OVN_TEST_GEN_FIXTURES"):
    # regenerate the committed parser fixtures: OVN_TEST_GEN_FIXTURES=<dir> python3 test_contract_fuzz.py (Part 1 fixture cases fail until they exist)
    dest = os.environ["OVN_TEST_GEN_FIXTURES"]
    os.makedirs(dest, exist_ok=True)
    for ref, fname, extra in (("base", "clean.ndjson", {}), ("boombad", "boom_bad.ndjson", {}),
                              ("slow", "timeout.ndjson", {"OVN_FUZZ_REQUEST_TIMEOUT_S": "1", "OVN_FUZZ_MAX_EXAMPLES": "3"})):
        e = {"OVN_FUZZ_KEEP_REPORT": os.path.join(dest, fname)}
        e.update(extra)
        r = run_fuzz(ref, fresh("state"), args=["--no-record"], env=e)
        print("generated %s: %s" % (fname, (r["res"] or {}).get("summary")))
    finish()

# ---- control for the liveness helper itself
sp = subprocess.Popen(["sleep", "30"])
ok("helper control: alive() sees a live process", alive(sp.pid))
sp.kill()
sp.wait()
ok("helper control: alive() sees a killed+reaped process as gone", not alive(sp.pid))

print("== first run, no baseline")
st1 = fresh("state")
r = run_fuzz("boom", st1)
res = r["res"]
ok("exit code 0 and exactly one JSON verdict line", r["rc"] == 0 and res is not None and r["out"].strip().count("\n") == 0, (r["rc"], r["out"][-300:], r["err"][-300:]))
ok("no baseline => FLAG 'no baseline: N signatures observed'", res and res["verdict"] == "FLAG" and re.search(r"^no baseline: \d+ signatures observed", res["summary"]), res and res["summary"])
ok("the 500 route is among the recorded signatures", SIG_BOOM in (sigs(r) or []), sigs(r))
ok("verdict carries the excluded-route count", res and res["details"].get("operations_excluded") == 1 and "excluded 1/" in res["summary"], res and res["details"])
ok("a first run does NOT write a baseline (human step only)", not os.path.exists(os.path.join(st1, "qa_shadow", "contract_fuzz_baseline_stubrepo.json")))
ok("one shadow row recorded", len(shadow_rows(st1)) == 1 and shadow_rows(st1)[0]["gate"] == "contract_fuzz" and shadow_rows(st1)[0]["mode"] == "shadow")
r = run_fuzz("boom", st1, args=["--no-record"])
ok("--no-record writes no shadow row", len(shadow_rows(st1)) == 1)
ok("shadow metadata: repo, ref, sha, schemathesis version, mode", res["repo"] == "stubrepo" and res["details"]["sha"] == REFS["boom"]
   and res["details"]["schemathesis_version"] and res["details"]["startup_s"] is not None)
ok("hermetic: no outbound attempt on a plain app", res["details"]["blocked_outbound"] == 0, res["details"])
ok("no temp dir / worktree left behind", leftovers() == ([], 1), leftovers())

print("== baseline flow: (a) new 500, (b) schema violation, (c) mutation control, (d) accept+rerun, (e) only the new signature")
st2 = fresh("state")
r = run_fuzz("base", st2, args=["--accept-baseline"])
ok("--accept-baseline on the clean app writes the baseline (0 signatures)", r["res"]["verdict"] == "PASS" and "baseline accepted" in r["res"]["summary"]
   and os.path.exists(os.path.join(st2, "qa_shadow", "contract_fuzz_baseline_stubrepo.json")), r["res"])
r_a = run_fuzz("boom", st2)
ok("(a) a route raising an unhandled exception => FLAG naming exactly that signature", r_a["res"]["verdict"] == "FLAG"
   and r_a["res"]["details"].get("new") == [SIG_BOOM], r_a["res"]["details"].get("new"))
r_b = run_fuzz("bad", st2)
ok("(b) a response violating its declared schema => FLAG naming exactly that signature", r_b["res"]["verdict"] == "FLAG"
   and r_b["res"]["details"].get("new") == [SIG_BAD], r_b["res"]["details"].get("new"))
r_c = run_fuzz("base", st2)
ok("(c) MUTATION CONTROL: the same app with the bug removed => PASS", r_c["res"]["verdict"] == "PASS" and not r_c["res"]["details"].get("new"), r_c["res"])
ok("(b)->(c) FLAG then PASS on the same baseline", (r_b["res"]["verdict"], r_c["res"]["verdict"]) == ("FLAG", "PASS"))
ok("a FLAG never becomes FAIL and the run is shadow", r_a["rc"] == 0 and r_a["res"]["mode"] == "shadow")
st3 = fresh("state")
run_fuzz("boom", st3, args=["--accept-baseline"])
r_d = run_fuzz("boom", st3)
ok("(d) accepting the baseline then re-running the same code => PASS", r_d["res"]["verdict"] == "PASS" and r_d["res"]["details"]["baseline_signatures"] >= 1, r_d["res"])
r_e = run_fuzz("boom2", st3)
ok("(e) a new 500 route after the baseline => FLAG listing exactly the new signature", r_e["res"]["verdict"] == "FLAG" and r_e["res"]["details"].get("new") == [SIG_BOOM2]
   and SIG_BOOM2 in r_e["res"]["summary"], r_e["res"]["details"].get("new"))
r_f = run_fuzz("base", st3)
ok("a signature that disappeared is reported as 'fixed' and the verdict stays PASS", r_f["res"]["verdict"] == "PASS" and SIG_BOOM in r_f["res"]["details"]["fixed"]
   and r_f["res"]["details"]["fixed_count"] == 1, r_f["res"]["details"].get("fixed"))
r_g = run_fuzz("boom", st3, env={"OVN_FUZZ_SEED": "7"})
ok("a baseline recorded with another seed is not comparable => UNVERIFIED (re-accept)", r_g["res"]["verdict"] == "UNVERIFIED" and "different fuzz parameters" in r_g["res"]["summary"],
   r_g["res"]["summary"])

print("== (f) excluded routes are never requested")
reset_hits()
r = run_fuzz("base", fresh("state"), args=["--no-record"])
ok("(f) the URL-fetching route is never hit", r["res"]["verdict"] in ("FLAG", "PASS") and "fetch:" not in hits(), hits())
ok("(f) exclusion count matches what schemathesis itself dropped", "exclude_count_mismatch" not in r["res"]["details"], r["res"]["details"])
reset_hits()
r = run_fuzz("base", fresh("state"), cfgpath=stub_cfg(exclude=()), args=["--no-record"])
ok("(f) NEGATIVE control: without the exclusion the same route IS requested", "fetch:" in hits() and r["res"]["details"]["operations_excluded"] == 0, hits())
reset_hits()

print("== auth plumbing")
r = run_fuzz("base", fresh("state"), cfgpath=stub_cfg(auth=True), args=["--no-record"])
ok("throwaway-user bearer token reaches the app (the token-gated route is exercised)", SIG_PRIV in (sigs(r) or []), sigs(r))
av = r["res"]["details"].get("argv") or []
ok("the token reaches schemathesis via config file + env, NOT argv: no credential flag, no '***' (a redacted secret), no token in the recorded argv",
   av and "-H" not in av and "--header" not in av and "--config-file" in av and TOKEN not in " ".join(av) and "***" not in " ".join(av), av)
ok("recorded argv = what really ran: nice prefix, -w 1, phases, checks, seed, report ndjson",
   av[:len(cf.qc.cpu_prefix())] == cf.qc.cpu_prefix() and adj(av, "-w", "1") and adj(av, "--phases", "examples,fuzzing") and adj(av, "--checks", cf.CHECKS)
   and adj(av, "--seed", "42") and adj(av, "--report", "ndjson") and "--no-shrink" in av, av)
r = run_fuzz("base", fresh("state"), args=["--no-record"])
ok("NEGATIVE control: without the auth bootstrap that route only answers 401", SIG_PRIV not in (sigs(r) or []), sigs(r))
bad_auth = stub_cfg(auth=True)
cfgd = json.load(open(bad_auth))
cfgd["stubrepo"]["auth"]["login"]["path"] = "/ok"          # GET-only route => login fails
json.dump(cfgd, open(bad_auth, "w"))
r = run_fuzz("base", fresh("state"), cfgpath=bad_auth, args=["--no-record"])
ok("a failed auth bootstrap is UNVERIFIED (infra), never FAIL", r["res"]["verdict"] == "UNVERIFIED" and "auth bootstrap" in r["res"]["summary"], r["res"]["summary"])

print("== (g) infra problems are UNVERIFIED")
r = run_fuzz("failstart", fresh("state"), args=["--no-record"])
ok("(g) an app that fails to start => UNVERIFIED 'app failed to start'", r["res"]["verdict"] == "UNVERIFIED" and "app failed to start" in r["res"]["summary"], r["res"]["summary"])
ok("(g) the startup failure text is shown redacted (seeded secret replaced, tail present)", "***" in r["res"]["summary"] and "stub boot failure" in r["res"]["summary"], r["res"]["summary"])
ok("(g) failed start leaves nothing behind", leftovers() == ([], 1), leftovers())
r = run_fuzz("slow", fresh("state"), args=["--no-record"], env={"OVN_FUZZ_TIMEOUT_S": "5", "OVN_FUZZ_REQUEST_TIMEOUT_S": "8"}, cfgpath=stub_cfg(pidfile=True))
ok("(g) schemathesis timeout (stub that sleeps) => UNVERIFIED 'timeout', within the cap + kill grace", r["res"]["verdict"] == "UNVERIFIED"
   and "timeout" in r["res"]["summary"] and r["elapsed"] < 5 + 25, (r["res"]["summary"], r["elapsed"]))
ok("(g) timeout leaves nothing behind and the app + its same-group child are gone", leftovers() == ([], 1)
   and not any(alive(int(x)) for x in open(PIDF).read().split()), (leftovers(), open(PIDF).read()))
r = run_fuzz("slow", fresh("state"), args=["--no-record"], env={"OVN_FUZZ_TIMEOUT_S": "120", "OVN_FUZZ_REQUEST_TIMEOUT_S": "1"})
ok("(g) NEGATIVE control: with a real request timeout the hang is a network_error signature, not UNVERIFIED", r["res"]["verdict"] == "FLAG" and SIG_SLOW in (sigs(r) or []),
   (r["res"]["verdict"], sigs(r)))
r = run_fuzz("base", fresh("state"), cfgpath=stub_cfg(venv="/nonexistent/python"), args=["--no-record"])
ok("no venv => UNVERIFIED 'no venv'", r["res"]["verdict"] == "UNVERIFIED" and "no venv" in r["res"]["summary"], r["res"]["summary"])
r = run_fuzz("base", fresh("state"), args=["--no-record"], env={"OVN_FUZZ_SCHEMATHESIS": "/nonexistent/st", "PATH": "/usr/bin:/bin"})
ok("schemathesis missing => UNVERIFIED", r["res"]["verdict"] == "UNVERIFIED" and "schemathesis missing" in r["res"]["summary"], r["res"]["summary"])
r = run_fuzz("deadbeefdeadbeef", fresh("state"), args=["--no-record"])
ok("unresolvable ref => UNVERIFIED", r["res"]["verdict"] == "UNVERIFIED" and "cannot resolve ref" in r["res"]["summary"], r["res"]["summary"])

print("== (h) NA cases")
r = run_fuzz("base", fresh("state"), repo="billwatch", args=["--no-record"])
ok("(h) unknown/unconfigured repo => NA 'repo not configured'", r["rc"] == 0 and r["res"]["verdict"] == "NA" and "repo not configured" in r["res"]["summary"], r["res"])
r = run_fuzz("base", fresh("state"), args=["--no-record"], env={"OVN_CONTRACT_FUZZ": "off"})
ok("kill switch => NA", r["res"]["verdict"] == "NA" and "OVN_CONTRACT_FUZZ=off" in r["res"]["summary"], r["res"])

print("== (i) fixed seed => identical signature sets")
ra = run_fuzz("mixed", fresh("state"), args=["--no-record"], env={"OVN_FUZZ_MAX_EXAMPLES": "25"})
rb = run_fuzz("mixed", fresh("state"), args=["--no-record"], env={"OVN_FUZZ_MAX_EXAMPLES": "25"})
ok("(i) two runs, same seed => identical, non-trivial signature sets", sigs(ra) == sigs(rb) and len(sigs(ra) or []) >= 3 and {SIG_BOOM, SIG_BOOM2, SIG_BAD} <= set(sigs(ra)),
   (sigs(ra), sigs(rb)))

print("== (j) no secret or token ever printed")
st4 = fresh("state")
outs = []
for ref, kw in (("failstart", {}), ("die", {"cfgpath": stub_cfg(auth=True)}), ("mixed", {"cfgpath": stub_cfg(auth=True)})):
    r = run_fuzz(ref, st4, args=["--accept-baseline"] if ref == "mixed" else [], **kw)
    outs.append((ref, r))
die_r = dict(outs)["die"]
ok("(j) the die-on-request run really exercised the leak path (app died, log tail was summarised)", die_r["res"]["verdict"] == "UNVERIFIED"
   and "died during the fuzz" in die_r["res"]["summary"] and "***" in die_r["res"]["summary"], die_r["res"]["summary"])
blob = "".join(r["out"] + r["err"] for _, r in outs)
for root_, _, files in os.walk(st4):
    for fn in files:
        blob += open(os.path.join(root_, fn), errors="replace").read()
ok("(j) seeded secret absent from stdout, stderr, shadow rows and the baseline", SECRET not in blob, [m.start() for m in re.finditer(re.escape(SECRET), blob)][:3])
ok("(j) throwaway bearer token absent from stdout, stderr, shadow rows and the baseline", TOKEN not in blob and "Bearer " + TOKEN not in blob)
ok("(j) the baseline stores signatures only (no bodies, no tokens)", all(re.match(r"^[A-Z]+ \S+ \[\w+\] \S+$", s) for s in json.load(
    open(os.path.join(st4, "qa_shadow", "contract_fuzz_baseline_stubrepo.json")))["signatures"]))

print("== outbound guard")
reset_hits()
r = run_fuzz("callout", fresh("state"), args=["--no-record"])
d = r["res"]["details"]
h = hits()
ok("guard: the app's outbound DNS + connect attempts were blocked and counted", d["blocked_outbound"] >= 2 and "stub-host.invalid" in d.get("blocked_outbound_hosts", []), d)
ok("guard: the connect to 192.0.2.1 was refused by the guard, not attempted", "callout:192.0.2.1:" in h and "callout:CONNECTED" not in h and "guard" in h, h)
ok("guard: the summary reports the blocked attempts and does not claim a hard guarantee", re.search(r"blocked \d+ outbound attempt\(s\) \(in-process guard", r["res"]["summary"])
   and "never left" not in r["res"]["summary"], r["res"]["summary"])

def mutant_run(label, anchor_fn, old, new, ref, state, **kw):
    md_ = mutant_dir("m-" + label)
    mutate(md_, anchor_fn, old, new)
    return run_fuzz(ref, state, script=os.path.join(md_, "contract_fuzz.py"), **kw)


print("== outbound guard holds under the async paths too (uvloop would bypass a Python-level guard)")
HAS_UV = subprocess.run([APP_PY, "-c", "import uvloop"], capture_output=True).returncode == 0
print("  note: stub python %s uvloop" % ("HAS" if HAS_UV else "does NOT have"))
reset_hits()
r = run_fuzz("acallout", fresh("state"), args=["--no-record"])
d = r["res"]["details"]
h = hits()
ok("async guard: asyncio.open_connection to .invalid and 192.0.2.1 is blocked AND counted", d.get("blocked_outbound", 0) >= 2
   and "stub-host.invalid" in d.get("blocked_outbound_hosts", []) and "192.0.2.1" in d.get("blocked_outbound_hosts", []), d)
ok("async guard: both attempts were refused by the guard (no CONNECTED, no real resolver/timeouts)", "acallout:CONNECTED" not in h
   and h.count("blocked by contract_fuzz guard") >= 2 and "TimeoutError" not in h, h)
if HAS_UV:
    md_ = mutant_dir("m-M11")
    mutate(md_, "contract_fuzz.py", 'for _m in ("aiodns", "pycares", "uvloop"):', 'for _m in ("aiodns", "pycares"):')
    mutate(md_, "contract_fuzz.py", 'access_log=False, loop="asyncio")', 'access_log=False)')
    reset_hits()
    r = run_fuzz("acallout", fresh("state"), args=["--no-record"], script=os.path.join(md_, "contract_fuzz.py"))
    ok("MUTATION M11 (old launcher: loop=auto, uvloop importable): the async-guard assertions above would FAIL - nothing blocked, nothing counted",
       r["res"]["details"]["blocked_outbound"] == 0 and "blocked by contract_fuzz guard" not in hits(), (r["res"]["details"], hits()))
else:
    ok("M11 control needs uvloop in the stub python (absent: %s); the guard assertions above still ran" % APP_PY, not os.environ.get("OVN_REQUIRE_QA_VENV"))
reset_hits()

print("== a transient ReadTimeout is re-checked once; a repeating one stays a signature")
FLAKY_MARK = os.path.join(WORK, "flaky.marker")


def flaky_cfg():
    try:
        os.unlink(FLAKY_MARK)
    except OSError:
        pass
    return stub_cfg(env={"STUB_FLAKY": FLAKY_MARK})


r = run_fuzz("flaky", fresh("state"), cfgpath=flaky_cfg(), args=["--no-record"], env={"OVN_FUZZ_REQUEST_TIMEOUT_S": "1"})
d = r["res"]["details"]
ok("transient: a first-request-only timeout is NOT a signature but is counted as details.transient_network_errors", SIG_FLAKY not in (sigs(r) or [])
   and d.get("transient_network_errors") == [SIG_FLAKY] and d.get("transient_network_error_count") == 1, (sigs(r), d.get("transient_network_errors")))
r2 = run_fuzz("slow", fresh("state"), args=["--no-record"], env={"OVN_FUZZ_REQUEST_TIMEOUT_S": "1", "OVN_FUZZ_MAX_EXAMPLES": "3"})
ok("transient: NEGATIVE control - a route that times out every time stays a signature after the re-check", SIG_SLOW in (sigs(r2) or [])
   and not r2["res"]["details"].get("transient_network_errors"), (sigs(r2), r2["res"]["details"].get("transient_network_errors")))
md_ = mutant_dir("m-M15")
mutate(md_, "contract_fuzz.py", "if transients and deadline - time.time() > 10 and app_proc.poll() is None:", "if False:")
r = run_fuzz("flaky", fresh("state"), cfgpath=flaky_cfg(), args=["--no-record"], env={"OVN_FUZZ_REQUEST_TIMEOUT_S": "1"}, script=os.path.join(md_, "contract_fuzz.py"))
ok("MUTATION M15 (no re-check): the transient assertion above would FAIL - the spike becomes a signature", SIG_FLAKY in (sigs(r) or []), sigs(r))

print("== app dying mid-fuzz leaves no straggler in its group")
try:
    os.unlink(PIDF)
except OSError:
    pass
r = run_fuzz("die", fresh("state"), cfgpath=stub_cfg(auth=True, pidfile=True), args=["--no-record"])
dp = [int(x) for x in open(PIDF).read().split()]
time.sleep(0.3)
ok("died mid-fuzz: UNVERIFIED and BOTH the (dead) app and its same-group child are gone", r["res"]["verdict"] == "UNVERIFIED" and "died during the fuzz" in r["res"]["summary"]
   and not any(alive(x) for x in dp), (r["res"]["summary"], [(x, alive(x)) for x in dp]))
try:
    os.unlink(PIDF)
except OSError:
    pass
r = mutant_run("M13", "contract_fuzz.py", '                sweep_group(app_proc)\n                return V("UNVERIFIED", "app process died during the fuzz',
               '                return V("UNVERIFIED", "app process died during the fuzz', "die", fresh("state"), args=["--no-record"], cfgpath=stub_cfg(auth=True, pidfile=True))
dp = [int(x) for x in open(PIDF).read().split()]
time.sleep(0.3)
survived = [alive(x) for x in dp]
for x in dp:
    for sig in (15, 9):
        try:
            os.kill(x, sig)
        except OSError:
            pass
time.sleep(0.3)
ok("MUTATION M13 (no straggler sweep on a dead leader): the assertion above would FAIL - the child survives", any(survived), survived)

print("== (k) process group + temp dirs after a normal run")
try:
    os.unlink(PIDF)
except OSError:
    pass
r = run_fuzz("base", fresh("state"), cfgpath=stub_cfg(pidfile=True), args=["--no-record"])
pids = [int(x) for x in open(PIDF).read().split()]
ok("(k) the stub recorded its pid and a same-group child pid", len(pids) == 2 and all(pids))
ok("(k) after the run both are gone (ps stat)", not any(alive(x) for x in pids), [(x, alive(x)) for x in pids])
ok("(k) no cfuzz-*/qa-wt-* temp dir and no registered worktree left", leftovers() == ([], 1), leftovers())

print("== mutations (each copies the module with ONE line broken and re-runs the matching case)")


stm = fresh("state")
run_fuzz("base", stm, args=["--accept-baseline"])
r = mutant_run("M1", "contract_fuzz.py", "new = sorted(set(observed) - old)", "new = []", "boom", stm)
ok("MUTATION M1 (new-signature logic broken): (a) would FAIL - the mutant says PASS for a new 500", r["res"]["verdict"] == "PASS", r["res"])
reset_hits()
r = mutant_run("M2", "contract_fuzz.py", "    if patterns:\n        args += [", "    if False:\n        args += [", "base", fresh("state"), args=["--no-record"])
ok("MUTATION M2 (exclude regex not passed): (f) would FAIL - the fetch route is requested", "fetch:" in hits(), hits())
reset_hits()
r = mutant_run("M3", "contract_fuzz.py", "socket.socket.connect, socket.socket.connect_ex, socket.getaddrinfo, socket.gethostbyname = connect, connect_ex, getaddrinfo, gethostbyname",
               "pass", "callout", fresh("state"), args=["--no-record"])
ok("MUTATION M3 (guard not installed): the guard assertions would FAIL - nothing blocked, no guard message", r["res"]["details"]["blocked_outbound"] == 0
   and "guard" not in hits(), (r["res"]["details"], hits()))
reset_hits()
r = mutant_run("M4", "contract_fuzz.py", '    for s in sorted(secrets, key=len, reverse=True):\n        text = text.replace(s, "***")', "    pass",
               "failstart", fresh("state"), args=["--no-record"])
ok("MUTATION M4 (literal redaction broken): (j) would FAIL - the seeded secret reaches the output", SECRET in r["out"], r["out"][-300:])
try:
    os.unlink(PIDF)
except OSError:
    pass
r = mutant_run("M5", "contract_fuzz.py", "    if proc is None or proc.poll() is not None:\n        return\n    pgid = proc.pid", "    return\n    pgid = proc.pid", "base",
               fresh("state"), args=["--no-record"], cfgpath=stub_cfg(pidfile=True))
mp = [int(x) for x in open(PIDF).read().split()]
survived = [alive(x) for x in mp]
for x in mp:                                   # the mutant orphaned them: clean up by hand
    for sig in (15, 9):
        try:
            os.killpg(x, sig)
        except OSError:
            pass
        try:
            os.kill(x, sig)
        except OSError:
            pass
time.sleep(0.5)
ok("MUTATION M5 (kill_group disabled): (k) would FAIL - the app/child survive the run", any(survived), survived)
md6 = mutant_dir("m-M6")
mutate(md6, "contract_fuzz.py", 'if chk.get("status") != "failure":', 'if chk.get("status") != "failure" or True:')
p = subprocess.run([sys.executable, "-c", "import sys; sys.path.insert(0, %r); import contract_fuzz as c; print(c.parse_ndjson(%r)['signatures'])" % (md6, fx("boom_bad.ndjson"))],
                   capture_output=True, text=True)
ok("MUTATION M6 (parser ignores failed checks): the fixture assertions would FAIL - no signatures", p.stdout.strip() == "[]", p.stdout + p.stderr)
stm = fresh("state")
run_fuzz("base", stm, args=["--accept-baseline"])
r = mutant_run("M7", "contract_fuzz.py", 'if base_doc.get("fingerprint") != fp:', "if False:", "base", stm, env={"OVN_FUZZ_SEED": "7"})
ok("MUTATION M7 (fingerprint check removed): the seed-mismatch assertion would FAIL - the mutant compares anyway", r["res"]["verdict"] != "UNVERIFIED", r["res"])
r = mutant_run("M8", "contract_fuzz.py", "st_proc.wait(timeout=max(1.0, deadline - time.time()))", "st_proc.wait(timeout=max(1.0, deadline - time.time()) + 3600)", "slow", fresh("state"), args=["--no-record"],
               env={"OVN_FUZZ_TIMEOUT_S": "5", "OVN_FUZZ_REQUEST_TIMEOUT_S": "3"})
ok("MUTATION M8 (wall cap not enforced): the timeout assertion would FAIL - no 'exceeded the cap' verdict", "exceeded the 5s cap" not in r["res"]["summary"], r["res"]["summary"])

r = mutant_run("M14", "contract_fuzz.py", "cmd = build_cmd(st_bin, spec_path, base, pdir, list(args) + list(extra_args), cfg_file)",
               'cmd = build_cmd(st_bin, spec_path, base, pdir, list(args) + list(extra_args), cfg_file) + (["-H", "Authorization: Bearer %s" % token] if token else [])',
               "base", fresh("state"), cfgpath=stub_cfg(auth=True), args=["--no-record"])
av = r["res"]["details"].get("argv") or []
ok("MUTATION M14 (token back on argv): the no-credential-on-argv assertion would FAIL - '-H' / '***' show up in the recorded argv", "-H" in av and "***" in " ".join(av), av)
for lab, old, new, probe in (
        ("M16a", '"-w", "1", ', "", lambda a: not adj(a, "-w", "1")),
        ("M16b", "cmd = qc.cpu_prefix() + [st_bin]", "cmd = [st_bin]", lambda a: a[:1] != cf.qc.cpu_prefix()[:1]),
        ("M16c", '"--phases", PHASES, ', "", lambda a: "--phases" not in a)):
    r = mutant_run(lab, "contract_fuzz.py", old, new, "base", fresh("state"), args=["--no-record"])
    av = r["res"]["details"].get("argv") or []
    ok("MUTATION %s (argv drifted from the spec): the argv assertion above would FAIL" % lab, bool(av) and probe(av), av)

print("== final hygiene")
ok("nothing left behind after the whole suite (temp dirs, worktrees)", leftovers() == ([], 1), leftovers())
finish()
